### PR TITLE
Updates for latest tools

### PR DESCRIPTION
**Pull request by lolsborn**
The latest tools changed the paths of some executables.  I updated to reflect those changes along with adding the android-9 build target.

This change set will break for anyone using older versions of android sdk.

### CODE REVIEW

**Comment by jberkel** [comment]
Would be nice not to break older sdks...

**Comment by iNoles** [comment]
Actually, it break older revisions for tool but not sdk.

**Comment by n8han** [comment]
Hm. I merged in the other pull request which only changes the path for adb, since the other tools still seem to be available in platforms/<platform>/tools, but then I found this in the docs about that dir:

"This directory is used only by SDK Tools r7 and below for development tools that are specific to this platform version—it's not used by SDK Tools r8 and above."
http://developer.android.com/sdk/installing.html

So this is probably the better approach, changing the platform tools directory entirely.

**Comment by n8han** [comment]
merged this in

**Pull request merged**
