### PR TITLE
No Apklib extraction for the "provided" scope

### PR DESCRIPTION
**Pull request by fxthomas**
See [this discussion](https://groups.google.com/forum/?fromgroups=#!topic/scala-on-android/OuGYJtvQdZo) on the mailing list.

ApkLib dependencies in the "provided" scope should already be present (and compiled) in one of the dependencies, and thus don't need to be extracted in the subprojects.

### CODE REVIEW

**Comment by tomjadams** [comment]
Just a note, I get this same error & solved it by partially doing what is described on that mailing list post, which is to set `proguardInJars in Android := Seq()` (so it removes the Scala library). I then had to add proguard options to keep the Scala classes used in tests only but not in our production code. I have also validated the `dependsOn(main % "provided")` works.

**Comment by fxthomas** [comment]
@tomjadams : You won't have to change `proguardInJars` in the next version, it will automatically set the `provided` deps as `-libraryjars` in the Proguard config ;)

**Comment by tomjadams** [comment]
Awesome, that'd be great, I had no end of troubles with this, I burned several days time trying to get it working. Though I now know the code fairly intimately :)

**Comment by appamatto** [comment]
Merged into 0.6.4 branch. Thanks!

**Pull request closed without merging**
