### PR TITLE
support apklib dependencies

### PR DESCRIPTION
**Pull request by loganj**
Adds a key for specifying apklib dependencies, which may be fetched via ivy.  Extracts the apklibs, adds sources, runs aapt.

based on prior work by Matthew Willis at github.com/appamatto

### CODE REVIEW

**Comment by jberkel** [comment]
thanks! do you have a sample config to test this quickly?

**Comment by loganj** [comment]
I do, but now I'm thinking this may not be quite right.  

It unpacks the apklibs in a source generator, but each apklib goes into its own directory under `target/` instead of going into the `managedSourceDirectory`.  Thought that would be better, but it doesn't seem to play well with `sbt-idea` and may not with others.

I'll look into fixing that and then update the pull request with a test config.

Apologies for the premature PR.

**Comment by loganj** [comment]
Seems to play much more nicely with `sbt-idea` now.  

Here's a sample configuration that uses Action Bar Sherlock 4 beta:  https://gist.github.com/1709186/

**Comment by jberkel** [comment]
apk builds fine but when generating idea project files i'm getting: 
https://gist.github.com/1710077

**Comment by loganj** [comment]
That's odd... In my own project, I see the retrieval fail (which I assumed was a bug in sbt-idea related to the artifact type and/or resolvers, since other dependent tasks work), but the idea project generates fine.  

I am now seeing the same `IllegalArgumentException` when I add sbt-idea to the sample config, though.

Looking into it.  Thanks for vetting so carefully.

**Comment by loganj** [comment]
Well, that was more obvious than expected.  The ABS resolver was defined for the main project, but not inherited for the test project.  I've updated the sample config gist, should work now.

**Pull request merged**
