### PR TITLE
Remove managedSourceDirectories modification

### PR DESCRIPTION
**Pull request by mpeltonen**
This fixes adding correct source directories to Idea project files with
sbt-idea plugin version 1.4.0+. 

Plugin authors should not modify 'managedSourceDirectories' directly, 
but only provide 'sourceGenerator' which generates sources under a 
subdirectory of 'sourceManaged' setting of the scope as described here:
http://www.scala-sbt.org/0.12.3/docs/Howto/generatefiles.html

### CODE REVIEW

**Comment by mpeltonen** [comment]
This is related to this sbt-idea change: https://github.com/mpeltonen/sbt-idea/issues/209

**Comment by mpeltonen** [comment]
Getting this and #147 integrated into official android plugin would allow me to finish the android facet generation in sbt-idea (see https://github.com/mpeltonen/sbt-idea/issues/191).

**Comment by mpeltonen** [comment]
Thanks a lot! 

One more wish would be some stable (non-snapshot) release (RC for example, if 0.6.3 is not yet planned) of android-plugin in the near future, so that it would not block sbt-idea plugin release as you can't depend on snapshots on a release to Maven central.

**Comment by jberkel** [comment]
sure thing, really want to release a new version soon.

**Comment by jberkel** [comment]
also just gave @appamatto access to the artifactory repo, since he took over maintenance of the plugin i'll leave it to him to do the release. would be nice to get a few more PRs merged before that though.

**Pull request merged**
