### PR TITLE
Restore "android library project" support to 0.11 branch

### PR DESCRIPTION
**Pull request by rst**
This is lingering cleanup in the transition from sbt 0.7 to newer versions,
done against the 0.11 branch of the plugin.

It restores the "Android Library Project" functionality:  if an Android
project has other Android projects in its direct classPath dependencies,
and you build an APK for that project, it will include resources for the
base project and its dependencies, and the IDs will be made consistent.
(In fact, by generating the same R.java file for all of them, with the
appropriate package name for each; it's a kludge, but that's how the
stock library project support is working now, too.)

This differs slightly from the previous version, in that it will include
only Android projects declared as direct dependencies, and not all the
Android projects in the build.  There may be only one sbt-android build
on the planet complex enough that it makes sense to be this selective,
but it happens to be mine ;-).

(It might make sense to include resources for dependencies-of-dependencies,
but I'm not sure anyone has a practical use for that...)

There are two commits here.  The first works in the 0.10 and 0.11 versions
of the plugin, and gets deprecation warnings in 0.11.  The second eliminates
the deprecation warnings in 0.11, and breaks things completely in 0.10.  So,
if you want to update the current master (the 0.10 branch), cherry-pick the
first commit only.

### CODE REVIEW

**Comment by appamatto** [comment]
I'm getting errors from dex that it has already added com.actionbarsherlock.R (the generated R class from my apklib) and its inner classes. Is there a reason these would be going through dex more than once?

**Comment by rst** [comment]
Well... this code expects to have full access to the source of the "library project",
so it can recompile it; it doesn't do apklib.  (I regret to say I'm not entirely sure
what proper apklib support would entail, but whatever it is, this code doesn't
do that yet.)

So, if you've got the source on the classpath, and _also_ a binary apklib, that could 
conceivably cause this sort of issue.

Beyond that, I'm not sure what help I can offer, aside from a working config for
comparison purposes, which is here if it's any help:

  https://github.com/rst/shopping_assistant/tree/sbt10_with_libprojects

**Comment by appamatto** [comment]
I should have clarified--I am actually building from source with an Android library project without any .apklib involvement. I'm using sbt-0.11.1-SNAPSHOT.

The only difference I can see in our configurations is that I'm using PlainJavaProject settings as well. Also, my build doesn't run proguard. I'll try to see if messing with this changes anything.

**Comment by appamatto** [comment]
Removing PlainJavaProject settings (and moving my manifest and res/ to src/main) fixed things. It'd be nice to make this work with PlainJavaProject as well, maybe I can try that when I have more time to throw at it.

**Comment by rst** [comment]
Agreed.  FWIW, dxTask in AndroidInstall.scala looks like it logs the arguments
to the dexer at the 'debug' level, so entering

> set logLevel := Level.Debug

at an sbt interactive prompt may let you see them.  If there's any obvious duplication
in there, it may then be easier to walk it back through the settings and see where it's
coming from.  (The 'javaSource in Compile <<= (baseDirectory) (_ / "src")' from
PlainJavaProject.scala is a possible suspect --- I'd have expected ':=' instead of
'<<='.  But I could just be missing something; better to trace through what's going on
than to just start poking at things....)

**Comment by appamatto** [comment]
I've had another issue with this patch. It seems easy for the two R.java (and associated classes) of the dependency and main project to get out of sync. This seems to happen, for example, doing a 'clean' on the dependency.

I'd like to avoid cleaning my main project as well because my NDK build takes around 2 minutes.

**Comment by appamatto** [comment]
A little more information:

I have A depends on B depends on C.

> xsbt "project C" clean android:package-debug
> xsbt "project B" clean android:package-debug

At this point R.id.some_resource are identical in B and C.

> xsbt "project A" clean android:package-debug

Now A's build has updated B's R.java and it is no longer compatible with C. A's and B's are in sync though. I get a runtime error because C's classes have already been compiled and inlined the version of the constants in C's R.java.

**Comment by rst** [comment]
Ouch.

Unfortunately, what's going on here is that the "library" subproject has a file
(R.java) which actually depends on the _parent_ project source --- specifically,
the resources therein.  So, to make this consistent in all cases, the aapt
tasks need to not only look for "this project's dependencies", but also
"projects which have this as a dependent," so that everything gets the same
set of resource IDs regardless of build order.  

Which, in turn, means that if you have a build which contains a library project,
and two apps which depend on the library, then the apps would wind up 
getting built with each others' resources, and the library would also get the
combined set.  (Bias note:  I actually do have one of these.)

FWIW, that's what the 0.7 version of the library support did --- it found all the
Android projects in the build, and generated resources for the combined set
no matter which [sub]project it was building.  But that can cause problems too;
if you've got a build with multiple apps depending on a common library, each
of them could wind up with the resources of all the others, and that can cause
problems too.  (You don't necessarily want them sharing bulky assets, and
name conflicts are also potentially an issue.)

There's also the implementation issue of walking the sbt dependency tree
backwards (walking it forwards is bad enough!), but that's a more minor thing.

So, I'll need to think about this for a bit...

Thanks for the note.

**Comment by appamatto** [comment]
Looking at the android-maven-plugin apklib support, here's what they do:
1. Unpack all the apklib dependencies into a managed directory (unnecessary for us because for now we require the original source projects)
2. Invoke aapt once, passing all of the dependencies' unpacked res directories.

I think this is probably the way we should do it. About your earlier point on bulky libraries, right now there is no apklib functionality so these libraries will never be shared as such. In the meantime I'm enjoying the simplicity of the source-only build process. It makes things easier for when I need to change something in an underlying project.

My project's dependency graph (to demonstrate a possible use case):

Main depends on UI (which is an Android library project)
Zoo also depends on UI
UI depends on ActionBarSherlock (external dependency, Android library project)

This worked nicely when I was using maven. Zoo is essentially a harness for showing off the UI library. I structured it like this because my main app is huge, and it takes forever to get UI changes onto the device so I can iterate on them.

**Comment by rst** [comment]
If I understand you right, that's pretty much what this patch does _when the parent project is getting compiled_.  The problem is that when it's compiling the libraries only, it gets tunnel vision, and leaves out the parent app's resources.

**Comment by appamatto** [comment]
Does it even make sense to be using class files from dependencies directly? I don't understand how these are going to be correct if the compiler inlines id constants.

I'm wondering if the best way to solve this is to include src directories from the dependency in the parent's src directory list and likewise for res and assets. That way the dependency's build is not fiddled with in any way and all compilation happens in the parent project. It might be that an sbt dependsOn is not warranted here?

**Comment by rst** [comment]
That's one approach.  If you look at 'master' here:

  https://github.com/rst/shopping_assistant

you can see a half-baked version of that, with an unmodified plugin,
and everything done through stock sbt config.  The problem with that
is that the stock plugin's aapt tasks generate only one R.java file, not
one per "Android project" package --- so I wound up kludging around
that by giving the Library project a dummy R.java file that indirected
everything to the one in the parent package.

(After which, I tried to clean things up by, writing the code on
this patch.  Which works here, but seems to be, well... somewhat
brittle.)

**Comment by appamatto** [comment]
Well, I think that's more ideal--then the library should still be buildable by itself. I'll try tinkering with something along those lines.

**Comment by rst** [comment]
Another possible arrangement:  run aapt generation (at least for the library)
with --non-constant-id, and have the aapt-package task regenerate and
compile the R.java files only.  Which eliminates the "baked-in stale cookie"
problem...

**Comment by appamatto** [comment]
Would that allow the class files from the library project to be used?

**Comment by rst** [comment]
Well, the point of this option is to let you build class files which don't
have resource IDs baked in, so you can change them later.  (There's a
slight performance penalty, of course --- but since resource IDs are almost
invariably used as arguments to some framework routine that's a _lot_ more
expensive than a static field access, it probably doesn't amount to much in
most cases.)

**Comment by appamatto** [comment]
rst, I submitted a new pull request. I use the --non-constant-id option like you suggested.

https://github.com/jberkel/android-plugin/pull/73

**Comment by rst** [comment]
Probably superseded by appamatto's pull request 73...

**Comment by epabst** [comment]
logan.johnson ended up committing something similar in 68862a6099783bfb4d4335c2b819116026345ecf.

**Pull request closed without merging**
