### PR TITLE
Call process with seq

### PR DESCRIPTION
**Pull request by jbrechtel**
Using formatted strings to execute processes results in arguments with spaces in them not being escaped.  Using a Seq() instead will allow Process to escape the spaces correctly and in a platform independent way.  This should be the last thing needed to support spaces in paths on Windows.

### CODE REVIEW

**Comment by rst** [comment]
Just as a heads-up --- the redefinition of the aapt tasks here may have minor conflicts
with the ones on the refactor-manifest branch.  (As does my pull request 62, for
restoring some form of library project functionality, which hits this stuff more
extensively...)

**Comment by jbrechtel** [comment]
Ahh, didn't notice that.  These changes are pretty small...not sure what makes the most sense from Jan's perspective but I can rather easily do this work on top of yours instead.

**Comment by rst** [comment]
Well, I'm not sure how to play it.  FWIW, my thing may need a little more work.
If you read the comments there, you'll see someone found out the hard way that
it doesn't play well with PlainJavaProject settings... which is kind of awkward
because most of the "library projects" you'd want to use _are_ plain Java projects.
Unfortunately, since I don't do much plain Java myself, I haven't got a clear
timeline on putting in a fix...

**Comment by jberkel** [comment]
thanks, merged this for now, will worry about conflicts later.

**Pull request merged**
