### PR TITLE
Adding specific instrumentation runner 

### PR DESCRIPTION
**Pull request by charroch**
The ability to create your own runners:

in manifest:

```
    <instrumentation
        android:label="Tests" android:targetPackage="novoda.widget.tests"
        android:name="org.scalatest.tools.SpecRunner" />
```

in build.sbt:

```
    instrumentationRunner in Android := "org.scalatest.tools.SpecRunner",
```

I was thinking taking the name as task key from manifest but yield in complexity.

### CODE REVIEW

**Comment by jberkel** [comment]
hey carl, any chance you could rebase this against the current master ? it cannot be merged cleanly at the moment.

**Comment by charroch** [comment]
Could you try now? I lost my specs output because of the ITestListener... I might play with the latest plugin a bit more.

For info, I am using scalatest precompiled and installed on device will using the following runner:
https://gist.github.com/2405203

Either you can merge the changes or wait and I ll push new changes to ensure you only parse test results for unit tests

**Comment by jberkel** [comment]
it then might make sense to only use ITestListener when the standard runner is used i guess.

**Comment by charroch** [comment]
previously I just logged the output of ADB. I ll need to revisit.

**Comment by jberkel** [comment]
maybe you can make your scala testrunner produce some output compatible with google's ? then only one testlistener would be required.

**Comment by charroch** [comment]
We could close the pull request and I ll remake a request when I played a
bit more.

On 17 April 2012 14:14, Jan Berkel <
reply@reply.github.com

> wrote:
> 
> maybe you can make your scala testrunner produce some output compatible
> with google's ? then only one testlistener would be required.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jberkel/android-plugin/pull/127#issuecomment-5174707

## 

Kind Regards,
Carl-Gustaf Harroch

Directing Novoda through the mobile revolution
+44 07 725 721 005
http://novoda.com/blog

LinkedIn http://www.linkedin.com/in/carlharroch
Delicioushttp://www.delicious.com/charroch
 Google Profile http://www.google.com/profiles/charroch
Twitterhttp://www.twitter.com/charroch
 Google Calendarhttp://www.google.com/calendar/embed?src=novoda1%40googlemail.com&ctz=Europe/London
Google Talk/novoda1, Skype/novoda.com

[image: Novoda logo]

We are growing, join the fun! http://surl.novoda.com/job

**Pull request closed without merging**
