### PR TITLE
Port to sbt 0.10

### PR DESCRIPTION
**Pull request by philcali**

### CODE REVIEW

**Comment by philcali** [comment]
I believe I've ported the android plugin functionality over to sbt 10.x.

The entry point is at Android.scala.

TypedResources and MarketPublish will require settings to be pulled like:

```
seq(TypedResources.settings: _*)
```

Or in a build.scala

``` scala
val project = Project(
  "cool-dude", 
  file("."), 
  settings = Defaults.defaultSettings ++ TypedResources.settings
)
```

## New Tasks
- `list-devices`: prints out all running emulators and devices
- `android:emulator-start <avd>`: fires up an android emulator with specified avd (tries to auto-complete avd name)
- `android:emulator-stop`: kills running emulator

-- Philip Cali

**Comment by ricardolee** [comment]
Good work.

**Comment by philcali** [comment]
Thanks!

**Comment by philcali** [comment]
Minor refactorings were made:
- Android settings are not forced down your throat ... only the sdk path and some sdk commands
- An android library project is now super easy to create by including `AndroidBase.settings` to a project setting
- Default android project must now include `AndroidProject.androidSettings` for base, install, launch, ddm settings and tasks

**Comment by philcali** [comment]
Fixed a couple of problems that would occur in a multiple project configuration. Here's an example of a multiple project configuration in sbt 10.x using this plugin. Once the port is more finalized, this configuration could become a g8 template:

https://gist.github.com/1101854

**Comment by charroch** [comment]
When will this be pushed into main? Phil, you seem to have couple of branches that differs anyone specific that one needs to work against?

**Comment by jberkel** [comment]
@charroch just got back from my laptop-less holidays and will have a look at this soon.

**Comment by philcali** [comment]
@charroch work from this pull request branch. I started to differ from master on this branch, as it was intended to be merged in by jberkel after he reviews the code and is pleased by it (hopefully :) ). I'm actually on vacation this week (awesome!), so I won't be doing much responding until the weekend.

**Comment by charroch** [comment]
@philcali, Great stuff. I am working against your branch and trying to add instrumentation and some other settings change. I ll push when the master branch clears up

**Comment by jberkel** [comment]
@philcali converted one of my projects to sbt 0.10.x, however the skip-proguard setting doesn't work as expected:

```
> skip-proguard
[info] true
> android:package-debug
[info] Wrote
/Users/jan/projects/touri/app/src_managed/main/scala/com/zegoggles/touri/TR.scala
[info] Compiling 1 Java source to
/Users/jan/projects/touri/app/target/scala-2.8.1.final/classes...
ProGuard, version 4.4 
ProGuard is released under the GNU General Public License. The authors of all 
programs or plugins that link to it (sbt, scala, ...) therefore
must ensure that these programs carry the GNU General Public License as well.
```

**Comment by philcali** [comment]
Hmm, I'm looking into that...

Also, by convention, all the android plugin related settings and tasks have been placed in the `Android` configuration. So, to override the `skipProguard` setting, be sure to say:

``` scala
import AndroidKeys._

skipProguard in Android := true
```

I know that seems a bit verbose, but I believe it's the 10.x standard to place plugin settings in their own config. This convention is certainly open to discussion for this plugin. It's not hard to change that at all. I just tried by best to upgrade the plugin to how it might appear as a 10.x version.

**Comment by jberkel** [comment]
@philcali, that did it thanks.

**Comment by philcali** [comment]
@jberkel, Sweet!

**Comment by philcali** [comment]
@charroch I finally made my master mirror `sbt10_migration`. I had to force push it up because some of the history was rewritten in `sbt10_migration` to back port a commit. It is now safe to work from either branch.

**Comment by philcali** [comment]
I've created a [giter8 template](https://github.com/philcali/android-app.g8) for the new 0.10.x plugin, finally.

I also realize that a few things were broken: 
- `AndroidMarketPublish` settings would cause a runtime exception
- My naive approach to a `AndroidTestProject` did not cut it (now replaced with `AndroidTest.androidSettings`
- Started working on a migration guide (hopefully that will help)

**Forgot to mention**: the 0.10.x plugin has not been published to scala-tools yet. Make sure you publish the plugin locally using the README's _Hacking on the plugin_ instructions.

**Pull request merged**
