### PR TITLE
Android library project support

### PR DESCRIPTION
**Pull request by paulbutcher**
This adds Android library support. It hasn't been as well tested as I would like (I'm going to get onto that ASAP) but does at least basically work and doesn't seem to break anything as far as I can see.

Typed resources don't (yet) work properly with resources in libraries

I'd appreciate any and all comments on this - library support is pretty hairy so it's entirely possible I've missed something in all of this.

### CODE REVIEW

**Comment by paulbutcher** [comment]
TypedResources now work with resources in libraries (turned out to be much easier than I feared!)

**Comment by paulbutcher** [comment]
I've been giving this a pretty good kicking over the last week or so, and it seems pretty solid. Let me know if there's anything you want changing or clarifying to be able to merge this in :-)

**Comment by geeksville** [comment]
Cool - I'll pull this to my local repo and help test - I need this feature anyway.

**Comment by sattvik** [comment]
I've started using this in a project, and so far it has been working well.  Nice work.

**Comment by n8han** [comment]
geeksville did you find any problems, or anyone else?

**Comment by geeksville** [comment]
it works fine for my simple project.

**Pull request merged**
