### PR TITLE
Allow the market password to be stored in a file.

### PR DESCRIPTION
**Pull request by appamatto**
I use an Option[File] which will revert to the old behavior if the setting is None.

### CODE REVIEW

**Comment by jberkel** [comment]
I added a generic password caching mechanism to the plugin, to enable it:

```
  cachePasswords in Android := true
```

At the moment it's used by the github task and the jar signer.

**Comment by appamatto** [comment]
jberkel, I don't think this works for me. I do my release builds on jenkins which pulls directly from github without my intervention. Being able to specify a password file (optionally None) seems like a more general solution.

**Comment by jberkel** [comment]
the keystore passwords file is expected in a well known location `~/.sbt/sbt-android-plugin-passwords/keystore`. so just create that file (with `account=password` entries), enable password caching and it should work.

**Comment by appamatto** [comment]
Great, seems to work fine. Thanks!

**Pull request closed without merging**
