### PR TITLE
Simplify TypedResources usage a bit.

### PR DESCRIPTION
**Pull request by rst**
This patch redefines the 'TypedViewHolder' trait so that it can be
applied to anything with a findViewById method, using structural
typing --- without requiring anything other than the 'findViewById'
method itself to exist.  The 'def view = this' and 'def activity = this'
of the TypedViewHolder and TypedActivityHolder traits are no longer
required; it's now possible to say

  class MyActivity extends Activity with TypedViewHolder {
    ...
  }

without further ceremony.

For back-compatibility, TypedActivityHolder is still defined as a
synonym for TypedViewHolder (though TypedViewHolder serves for both,
and may be better named --- a TypedActivityHolder holds Views, not
Activities).

The implicit conversions in the TypedResource object are likewise
still defined, and still work.

### CODE REVIEW

**Comment by n8han** [comment]
One thing I've noticed with structural types and proguard is that they seem to increase the chances that it won't notice that a particular block of code is being used, so it will be removed. That may not be an issue here, for whatever reason, but I would try running this against a decent sized project that is using proguard first.

**Comment by rst** [comment]
FWIW, all my Positronic Net sample apps have been using a version of the
TypedViewHolder trait included here, without any obvious problems.  (I've
usually been calling it ViewFinder, but the code is the same.)  The biggest
are the UmbrellaToday weather-report fetcher, and my shopping-list assistant;
neither is the size of K9, but they're both nontrivial (particularly if you count the
Positronic Net library that they're getting linked with, which includes a small
ORM).

What these _don't_ use is the implicit conversions, or the anonymous 
TypedViewHolder subclasses they define.  But those anonymous subclasses
were there originally; I've just tweaked the definitions a bit.  So, I would be
surprised if there are problems here.

That said, I'd be happy to throw it at a decent sized project that uses the 
implicits, so long as it's known to build cleanly with the trunk or 0.11 version 
of the plugin...

**Comment by rst** [comment]
BTW, where I would expect structural typing to confuse the heck out of
ProGuard is if you're using it in a match, or something like that.  Which 
isn't what I'm doing; instead, I'm using it to define the self-type of the
ViewHolder trait:

trait TypedViewHolder {
  def findViewById( id: Int ): View
  def findView[T](tr: TypedResource[T]) = findViewById(tr.id).asInstanceOf[T]
}

In effect, it's just a trait with an abstract method in it; perhaps I should have
explained it that way instead.

In any case, by the time things get down to bytecode, every
class that extends the trait has a constructor that's getting explicitly
invoked someplace (these are the anonymous TypedView derivative
classes), unless it's a View or Activity which are already
explicitly protected by the ProGuard options in AndroidInstall.scala.

**Comment by n8han** [comment]
All right, I'll merge.

**Comment by rst** [comment]
Thank you kindly.

**Pull request merged**
