### PR TITLE
Move code to named package

### PR DESCRIPTION
**Pull request by mpeltonen**
Fix for #147 with package name derived from publishing organization and name

### CODE REVIEW

**Comment by mpeltonen** [comment]
Thanks!

Notice that this now means some changes to documentation wrt imports:

``` code
import org.scalasbt.androidplugin._
import org.scalasbt.androidplugin.AndroidKeys._
```

**Comment by jberkel** [comment]
right - i'm actually thinking about reverting this commit and inserting the package statement without moving the files - since now all existing PRs won't merge cleanly anymore.

**Comment by mpeltonen** [comment]
Ah, of course :(

**Comment by fxthomas** [comment]
@jberkel : Is it okay with you if I fix the interesting PRs into my new branch so that we can import everything at once later?

**Comment by jberkel** [comment]
@fxthomas yes, go for it

**Pull request merged**
