### PR TITLE
This is a first cut at restoring Paul Butcher's "Android Library Project" support, which seems to have gotten lost in the sbt upgrade shuffle.  (Paul says he's happy for someone else to do the work.)  This applies cleanly against the sbt 0.11 branch, but 

### PR DESCRIPTION
**Pull request by rst**
This is lingering cleanup in the transition from sbt 0.7 to newer versions.
It restores the "Android Library Project" functionality:  if an Android
project has other Android projects in its direct classPath dependencies,
and you build an APK for that project, it will include resources for the
base project and its dependencies, and the IDs will be made consistent.
(In fact, by generating the same R.java file for all of them, with the
appropriate package name for each; it's a kludge, but that's how the
stock library project support is working now, too.)

This differs slightly from the previous version, in that it will include
only Android projects declared as direct dependencies, and not all the
Android projects in the build.  There may be only one sbt-android build
on the planet complex enough that it makes sense to be this selective,
but it happens to be mine ;-).

(It might make sense to include resources for dependencies-of-dependencies,
but I'm not sure anyone has a practical use for that...)

### CODE REVIEW

**Comment by rst** [comment]
... but needs more testing there (to finish the comment).  I'll be kicking it more on
Sunday; if there's something else you'd like me to fix, let me know in the meantime
and I'll do what I can to take care of it...

**Comment by rst** [comment]
Seems to work with sbt 0.11 as-is, except for two scala 2.9 deprecation warnings
on "error(...)", for which it now wants "sys.error(...)".  I'm somewhat tempted to
replace it instead with "throw new RuntimeException(...)", which is the implementation
from the 2.8 Predef.scala, and will raise no warnings with either version.

(Test involved "rebuild the world" on a clean laptop --- building my library, one of its
bundled sample apps, and a separate sample app which uses Jeff Gilfelt's 
mapviewballoons as a library project.)

**Comment by rst** [comment]
sbt 0.11 branch in my repo now has the patch, and a two-liner to deal with the
deprecation warnings.  Could do a separate pull request from that branch if it
makes things easier; otherwise, I think this is good to go...

**Comment by appamatto** [comment]
Does this work for apklib dependencies as well, or only sbt-built projects?

**Comment by rst** [comment]
Right now, it requires the library project source to be managed as part of
the same SBT "build" --- I think that's a "no".  (I'd need a bit more details
on apklib than a quick Google search could come up with to know exactly
what's involved, but tracing through the sbt settings to identify the apklib
dependencies might well be the trickiest part of the job...)

**Comment by rst** [comment]
Just resubmitted a much neater version of this pull request; closing out
this one.

**Pull request closed without merging**
