### PR TITLE
Support for library projects.

### PR DESCRIPTION
**Pull request by appamatto**
Using the --non-constant-id option to aapt we make sure that the
library projects' ids are not inlined by the compiler.
Unfortunately we need to several R.java files, each identical but with
different packages, since the library projects will be looking for them there.

Thanks to rst--this code is based on his but uses a different method.

You need to set isLibraryProject in Android := true for all of the library projects. Only direct dependencies are included, but it is now safe to flatten your dependency tree because all of the compilation occurs in the parent project.

### CODE REVIEW

**Comment by rst** [comment]
Thanks.  Looks good --- unfortunately, I can't kick the tires right now,
but I'll do that on Sunday.

Just as a heads-up to all concerned, the aapt tasks are also tweaked
by jbrechtel's pull request 71 (which puts the args in a Seq so directory
names with spaces work right), and with the code on Jan's own
refactor-manifest branch (which changes manifest path handling a bit).

**Comment by appamatto** [comment]
Has anyone gotten a chance to look at this? I've been living on it for a while and it seems to be working so far.

**Comment by Macarse** [comment]
appamatto: Does it work with the new SDK?

**Comment by appamatto** [comment]
I'm not sure. I'm still on r13 because one of the library projects I depend on seemed to depend on it.

**Comment by jberkel** [comment]
Any chance you could test this on r15 and resubmit the current pull request so it applies cleanly?

**Comment by appamatto** [comment]
oops, that last submit was a mistake. I'll reapply the patch and submit a new pull request later.

**Comment by jrudolph** [comment]
What happened to this? Did any of this get into a recent version?

**Comment by jberkel** [comment]
no it never got included, would be great to have it.

**Pull request closed without merging**
